# Generated by Django 4.1.1 on 2022-09-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='core',
            old_name='excerpt',
            new_name='description',
        ),
    ]
