# Generated by Django 4.1.1 on 2022-09-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_excerpt_core_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='core',
            old_name='title',
            new_name='poll_title',
        ),
    ]
