# Generated by Django 4.1.1 on 2022-09-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_currentpolls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='core',
            name='slug',
        ),
    ]
